/// Current draft-class prospects (pre-signing staging), keyed by player_key (MD5 of name+pos+school). Bridges to Dim_NFLPlayers via gsis_id once signed.
table Dim_RookieProspect
	lineageTag: 8348a419-9666-434e-8853-9b007b832d8b

	/// Prospect key = MD5 of cleaned name + position + school (key).
	column PlayerKey
		dataType: string
		lineageTag: a69f64a6-473c-4b99-8ce5-f2609657be09
		summarizeBy: none
		sourceColumn: player_key

		annotation SummarizationSetBy = User

		annotation Synonyms = player key|prospect key|rookie key

		annotation SynonymCollection = ["player key","prospect key","rookie key"]

	/// Prospect display name.
	column PlayerName
		dataType: string
		lineageTag: 1c8d38fc-2821-4bf1-b73d-816ec2507ec6
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = User

		annotation Synonyms = player|name|prospect name|who

		annotation SynonymCollection = ["player","name","prospect name","who"]

	/// Normalized name used for cross-source matching.
	column PlayerNameClean
		dataType: string
		lineageTag: 92908fb5-565b-4e64-bb39-5625eb736c33
		summarizeBy: none
		sourceColumn: player_name_clean

		annotation SummarizationSetBy = User

		annotation Synonyms = clean name|normalized name|match name

		annotation SynonymCollection = ["clean name","normalized name","match name"]

	/// Prospect position (raw); links to Dim_Position.
	column PositionRaw
		dataType: string
		lineageTag: a8800231-dc12-4332-9c1d-7ad9500f7346
		summarizeBy: none
		sourceColumn: position_raw

		annotation SummarizationSetBy = User

		annotation Synonyms = position|pos|role

		annotation SynonymCollection = ["position","pos","role"]

	column SchoolRaw
		dataType: string
		lineageTag: c91f93bb-011b-4252-ab55-5a355600ff86
		summarizeBy: none
		sourceColumn: school_raw

		annotation SummarizationSetBy = User

		annotation Synonyms = school|college|raw school

		annotation SynonymCollection = ["school","college","raw school"]

	column HeightInches
		dataType: double
		lineageTag: 4d7546af-3f42-4070-8f6c-d06b5569ca49
		summarizeBy: none
		sourceColumn: height_inches

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation Synonyms = height|inches tall|how tall

		annotation SynonymCollection = ["height","inches tall","how tall"]

	/// Prospect weight in pounds.
	column Weight
		dataType: double
		lineageTag: 62a4b7f6-bdb8-498b-9673-b451f7bff1af
		summarizeBy: none
		sourceColumn: weight

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation Synonyms = weight|pounds|lbs

		annotation SynonymCollection = ["weight","pounds","lbs"]

	/// Draft class year.
	column DraftYear
		dataType: int64
		formatString: 0
		lineageTag: 826ca94c-5a50-4c4d-b536-0163a977844d
		summarizeBy: none
		sourceColumn: draft_year

		annotation SummarizationSetBy = User

		annotation Synonyms = draft year|class year|rookie year

		annotation SynonymCollection = ["draft year","class year","rookie year"]

	/// Source that introduced the prospect to the registry.
	column Source
		dataType: string
		lineageTag: 10566581-49d8-4eb3-b415-20588bf15c4f
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = User

		annotation Synonyms = source|origin|added by

		annotation SynonymCollection = ["source","origin","added by"]

	/// Date the prospect was added to the registry.
	column AddedDate
		dataType: string
		lineageTag: e455c13f-7d00-4f33-944f-738c5a0a5982
		summarizeBy: none
		sourceColumn: added_date

		annotation SummarizationSetBy = User

		annotation Synonyms = added date|date added|created

		annotation SynonymCollection = ["added date","date added","created"]

	column position_detail
		dataType: string
		lineageTag: b64ef7b2-4992-4917-9006-1b47ab035f49
		summarizeBy: none
		sourceColumn: position_detail

		annotation SummarizationSetBy = Automatic

	column position_group
		dataType: string
		lineageTag: 9316ab20-bfe6-4e96-91dd-fd758d3508e2
		summarizeBy: none
		sourceColumn: position_group

		annotation SummarizationSetBy = Automatic

	column side_of_ball
		dataType: string
		lineageTag: 87b6a10c-2827-4a9e-ad02-4e9d1625f362
		summarizeBy: none
		sourceColumn: side_of_ball

		annotation SummarizationSetBy = Automatic

	column fantasy_relevant
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 88064439-1e76-41a3-8d98-63ca3b986f29
		summarizeBy: none
		sourceColumn: fantasy_relevant

		annotation SummarizationSetBy = Automatic

	column school_canonical
		dataType: string
		lineageTag: c9906b0d-93c3-4960-83c1-7bf3d52a12eb
		summarizeBy: none
		sourceColumn: school_canonical

		annotation SummarizationSetBy = Automatic

	column conference
		dataType: string
		lineageTag: 70be458d-e51e-4638-96a2-f298c812f86b
		summarizeBy: none
		sourceColumn: conference

		annotation SummarizationSetBy = Automatic

	partition Dim_RookieProspect = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\benha\OneDrive\Documents\GitHub\Python-PowerBI-DynastyFantasyFootball\data\dim_rookie_prospect.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"gsis_id", "pfr_id", "cfb_id"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation Synonyms = Rookie Prospects|Prospects|Draft Class|Rookies|Prospect Dimension

	annotation SynonymCollection = ["Rookie Prospects","Prospects","Draft Class","Rookies","Prospect Dimension"]

