/// Dynasty ranking backbone: one row per snapshot, source, player, and format. Holds the universal overall/positional rank; source-specific stats live in the long metrics fact.
table Fact_DynastyRankings
	lineageTag: eb0043af-123f-4d08-a346-77999c9ae3b0

	/// Date the rankings were captured (YYYY-MM-DD). Use the latest snapshot for current ranks; manual-cadence time series.
	column SnapshotDate
		dataType: string
		lineageTag: a42d74de-ca8d-483c-b4e4-02b0648d555e
		summarizeBy: none
		sourceColumn: snapshot_date

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = snapshot|date|as of date|capture date

		annotation SynonymCollection = ["snapshot","date","as of date","capture date"]

	/// Ranking source (KTC, DynastySharks, FantasyPros).
	column SourceName
		dataType: string
		lineageTag: 62d49a4c-0146-4faa-bf81-5fe197a9c078
		summarizeBy: none
		sourceColumn: source_name

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = source|ranking source|provider|site

		annotation SynonymCollection = ["source","ranking source","provider","site"]

	/// The source's own player id/slug; not unique across sources.
	column SourcePlayerID
		dataType: string
		lineageTag: 9d4c6c43-44db-43fc-865c-bedc52afe6c3
		summarizeBy: none
		sourceColumn: source_player_id

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = source player id|player slug|source id

		annotation SynonymCollection = ["source player id","player slug","source id"]

	/// League format the ranking applies to (SF superflex, TEPP, IDP).
	column Format
		dataType: string
		lineageTag: b629c86c-45a0-479a-bdb1-e3c80a93880d
		summarizeBy: none
		sourceColumn: format

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = format|league format|scoring format|superflex

		annotation SynonymCollection = ["format","league format","scoring format","superflex"]

	/// Originating website/domain for the ranking.
	column SourceSite
		dataType: string
		lineageTag: 543ca236-2099-4401-bdfa-d6a879f5fed1
		summarizeBy: none
		sourceColumn: source_site

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = site|website|source site|domain

		annotation SynonymCollection = ["site","website","source site","domain"]

	/// Player display name as published by the source.
	column PlayerName
		dataType: string
		lineageTag: 45aa2ef1-d51c-4276-b526-834dc7d87caa
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = player|name|player name|who

		annotation SynonymCollection = ["player","name","player name","who"]

	/// Player position as published by the source (raw, pre-canonical).
	column PositionRaw
		dataType: string
		lineageTag: 7c96f06f-64e9-4941-82bb-e8157bed09a9
		summarizeBy: none
		sourceColumn: position_raw

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = position|pos|role|position raw

		annotation SynonymCollection = ["position","pos","role","position raw"]

	/// Player's NFL team abbreviation at capture.
	column NFLTeam
		dataType: string
		lineageTag: 0d22021a-01e3-404f-b540-f1c860b7712f
		summarizeBy: none
		sourceColumn: nfl_team

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = team|nfl team|club|pro team

		annotation SynonymCollection = ["team","nfl team","club","pro team"]

	/// Player age (years) joined from the registry at capture.
	column Age
		dataType: double
		lineageTag: 1a43129e-b6aa-4a15-b6ea-d922f72de08e
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation Synonyms = age|years old|player age

		annotation SynonymCollection = ["age","years old","player age"]

	/// Overall dynasty rank across all positions (1 = best). Lower is better.
	column OverallRank
		dataType: int64
		formatString: 0
		lineageTag: 26a89272-2bdc-4067-b6d7-e53d6acae784
		summarizeBy: sum
		sourceColumn: overall_rank

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = overall rank|rank|dynasty rank|ranking

		annotation SynonymCollection = ["overall rank","rank","dynasty rank","ranking"]

	/// Rank within the player's position (e.g. QB3). Lower is better.
	column PositionalRank
		dataType: int64
		formatString: 0
		lineageTag: 8e46913f-6452-4e86-a06a-429987f9dceb
		summarizeBy: sum
		sourceColumn: positional_rank

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = positional rank|position rank|pos rank|rank at position

		annotation SynonymCollection = ["positional rank","position rank","pos rank","rank at position"]

	/// nflverse universal player id; links to Dim_NFLPlayers.
	column GSISID
		dataType: string
		lineageTag: fc622479-fcfd-4e5c-b4e4-ad8c34894803
		summarizeBy: none
		sourceColumn: gsis_id

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = gsis id|player id|nfl id

		annotation SynonymCollection = ["gsis id","player id","nfl id"]

	/// Draft-class player key; links to Dim_RookieProspect for rookies.
	column PlayerKey
		dataType: string
		lineageTag: 399c5e7b-0b8f-4b85-8bc7-cc07c7506414
		summarizeBy: none
		sourceColumn: player_key

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = player key|rookie key|prospect key

		annotation SynonymCollection = ["player key","rookie key","prospect key"]

	/// Composite key (snapshot-source-player-format) linking to the long metrics fact.
	column MetricIndex
		dataType: string
		lineageTag: 03e447aa-e370-498a-b68c-abd945bda1d1
		summarizeBy: none
		sourceColumn: MetricIndex

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = metric index|row key|join key

		annotation SynonymCollection = ["metric index","row key","join key"]

	/// Player identity key = source_name|source_player_id; links to the crosswalk.
	column SourceUID
		dataType: string
		lineageTag: e2c283a3-e61f-47b6-9012-934dcb201c24
		summarizeBy: none
		sourceColumn: source_uid

		annotation SummarizationSetBy = Automatic

		annotation Synonyms = source uid|player uid|identity key

		annotation SynonymCollection = ["source uid","player uid","identity key"]

	partition Fact_DynastyRankings = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\benha\OneDrive\Documents\GitHub\Python-PowerBI-DynastyFantasyFootball\data\fact_dynasty_rankings.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Inserted Merged Column" = Table.AddColumn(Source, "MetricIndex", each Text.Combine({"20260606-", [source_name], "-", [source_player_id], "-", [format]}))
				in
				    #"Inserted Merged Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation Synonyms = Dynasty Rankings|Rankings|Dynasty Board|Player Rankings|Value Board

	annotation SynonymCollection = ["Dynasty Rankings","Rankings","Dynasty Board","Player Rankings","Value Board"]

